DROP TABLE IF EXISTS comics;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS codes;

CREATE TABLE artists (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT NOT NULL,
    passhash TEXT NOT NULL,
    isadmin BOOLEAN NOT NULL
);

CREATE TABLE comics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    fileext TEXT NOT NULL,
    artistid INTEGER NOT NULL,
    FOREIGN KEY (artistid)
        REFERENCES artists(id)
);

CREATE TABLE codes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL,
    expired BOOLEAN NOT NULL
)